# Generated by Django 5.2.3 on 2025-07-01 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_provider', models.CharField(choices=[('Google', 'Google'), ('OpenAI', 'OpenAI'), ('Other', 'Diğer')], default='Google', max_length=50, verbose_name='Sağlayıcı')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Yapılandırma Adı')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model Adı (örn: gemini-1.5-flash-latest)')),
                ('api_key', models.CharField(help_text='Bu modele ait API anahtarı.', max_length=255)),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Model Yapılandırması',
                'verbose_name_plural': 'AI Model Yapılandırmaları',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_scan_angle_setting', models.FloatField(default=360.0, verbose_name='Yatay Tarama Açısı')),
                ('h_step_angle_setting', models.FloatField(default=10.0, verbose_name='Yatay Adım Açısı')),
                ('v_scan_angle_setting', models.FloatField(default=180.0, verbose_name='Dikey Tarama Açısı')),
                ('v_step_angle_setting', models.FloatField(default=10.0, verbose_name='Dikey Adım Açısı')),
                ('steps_per_revolution_setting', models.IntegerField(default=4096, verbose_name='Motor Adım/Tur')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Başlangıç Zamanı')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Bitiş Zamanı')),
                ('status', models.CharField(choices=[('RUN', 'Çalışıyor'), ('CMP', 'Tamamlandı'), ('INT', 'Kesildi'), ('ERR', 'Hata'), ('ISP', 'Yetersiz Nokta')], default='RUN', max_length=3, verbose_name='Durum')),
                ('point_count', models.IntegerField(default=0, verbose_name='Geçerli Nokta Sayısı')),
                ('calculated_area_cm2', models.FloatField(blank=True, null=True, verbose_name='2D Alan (cm²)')),
                ('perimeter_cm', models.FloatField(blank=True, null=True, verbose_name='2D Çevre (cm)')),
                ('max_width_cm', models.FloatField(blank=True, null=True, verbose_name='Maks. Genişlik (cm)')),
                ('max_depth_cm', models.FloatField(blank=True, null=True, verbose_name='Maks. Derinlik (cm)')),
                ('max_height_cm', models.FloatField(blank=True, null=True, verbose_name='Maks. Yükseklik (cm)')),
                ('calculated_volume_cm3', models.FloatField(blank=True, null=True, verbose_name='3D Hacim (cm³)')),
                ('ai_commentary', models.TextField(blank=True, null=True, verbose_name='AI Yorumu')),
            ],
            options={
                'verbose_name': 'Tarama Kaydı',
                'verbose_name_plural': 'Tarama Kayıtları',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ScanPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('derece', models.FloatField(verbose_name='Yatay Açı (°)')),
                ('dikey_aci', models.FloatField(blank=True, null=True, verbose_name='Dikey Açı (°)')),
                ('mesafe_cm', models.FloatField(verbose_name='Mesafe (cm)')),
                ('hiz_cm_s', models.FloatField(blank=True, null=True, verbose_name='Hız (cm/s)')),
                ('x_cm', models.FloatField(blank=True, null=True)),
                ('y_cm', models.FloatField(blank=True, null=True)),
                ('z_cm', models.FloatField(blank=True, null=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='scanner.scan')),
            ],
            options={
                'verbose_name': 'Tarama Noktası',
                'verbose_name_plural': 'Tarama Noktaları',
                'ordering': ['timestamp'],
            },
        ),
    ]
