# Generated by Django 5.2.3 on 2025-10-26 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='scan_type',
            field=models.CharField(choices=[('MAN', 'Manuel Haritalama'), ('AUT', 'Otonom Sürüş')], default='MAN', max_length=3, verbose_name='Tarama Tipi'),
        ),
    ]
