# Generated by Django 5.2.3 on 2025-11-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scan_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanpoint',
            name='h_sensor_distance',
            field=models.FloatField(blank=True, help_text='Yatay motor üzerindeki sensör okuması', null=True, verbose_name='H-Sensör Mesafesi (cm)'),
        ),
        migrations.AddField(
            model_name='scanpoint',
            name='v_sensor_distance',
            field=models.FloatField(blank=True, help_text='Dikey motor üzerindeki sensör okuması', null=True, verbose_name='V-Sensör Mesafesi (cm)'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='mesafe_cm',
            field=models.FloatField(verbose_name='Ana Mesafe (cm)'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='x_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='X Koordinatı (cm)'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='y_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Y Koordinatı (cm)'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='z_cm',
            field=models.FloatField(blank=True, null=True, verbose_name='Z Koordinatı (cm)'),
        ),
    ]
