# Generated by Django 5.2.8 on 2025-11-06 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_scanpoint_h_sensor_distance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base64_image', models.TextField(verbose_name='Base64 Görüntü')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Zaman Damgası')),
                ('effect', models.CharField(choices=[('none', 'Normal'), ('grayscale', 'Gri Tonlama'), ('edges', 'Kenar Algılama'), ('invert', 'Ters Çevir')], default='none', max_length=20, verbose_name='Efekt')),
                ('pan_angle', models.FloatField(verbose_name='Pan Açısı (Yatay)')),
                ('distance_info', models.CharField(help_text="Örn: '45.1 cm' veya 'Sensör kapalı'", max_length=50, verbose_name='Mesafe Bilgisi')),
            ],
            options={
                'verbose_name': 'Kamera Yakalama',
                'verbose_name_plural': 'Kamera Yakalamaları',
                'ordering': ['-timestamp'],
            },
        ),
    ]
