# Generated by Django 5.2.8 on 2025-11-07 19:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_cameracapture'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
                ('level', models.CharField(choices=[('INFO', 'Bilgi'), ('WARNING', 'Uyarı'), ('ERROR', 'Hata'), ('CRITICAL', 'Kritik')], default='INFO', max_length=20, verbose_name='Seviye')),
                ('message', models.TextField(verbose_name='Mesaj')),
                ('component', models.CharField(help_text='camera, motor, sensor, etc.', max_length=50, verbose_name='Bileşen')),
            ],
            options={
                'verbose_name': 'Sistem Logu',
                'verbose_name_plural': 'Sistem Logları',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='cameracapture',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Kamera Fotoğrafı', 'verbose_name_plural': 'Kamera Fotoğrafları'},
        ),
        migrations.AlterField(
            model_name='aimodelconfiguration',
            name='api_key',
            field=models.CharField(help_text='Bu modele ait API key (güvenli saklanmalı)', max_length=255, verbose_name='API Anahtarı'),
        ),
        migrations.AlterField(
            model_name='aimodelconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma'),
        ),
        migrations.AlterField(
            model_name='aimodelconfiguration',
            name='model_name',
            field=models.CharField(help_text='Örn: gemini-1.5-flash-latest veya gpt-4-turbo', max_length=100, verbose_name='Model Adı'),
        ),
        migrations.AlterField(
            model_name='aimodelconfiguration',
            name='model_provider',
            field=models.CharField(choices=[('Google', 'Google (Gemini)'), ('OpenAI', 'OpenAI (GPT)'), ('Anthropic', 'Anthropic (Claude)'), ('Other', 'Diğer')], default='Google', max_length=50, verbose_name='Sağlayıcı'),
        ),
        migrations.AlterField(
            model_name='aimodelconfiguration',
            name='name',
            field=models.CharField(help_text="Örn: 'Production Gemini' veya 'Test GPT-4'", max_length=100, unique=True, verbose_name='Yapılandırma Adı'),
        ),
        migrations.AlterField(
            model_name='aimodelconfiguration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme'),
        ),
        migrations.AlterField(
            model_name='cameracapture',
            name='base64_image',
            field=models.TextField(help_text='Base64 encoded JPEG/PNG görüntü', verbose_name='Base64 Görüntü'),
        ),
        migrations.AlterField(
            model_name='cameracapture',
            name='distance_info',
            field=models.CharField(blank=True, help_text="Ultrasonik sensör mesafe okuması (örn: '45.1 cm')", max_length=100, null=True, verbose_name='Mesafe Bilgisi'),
        ),
        migrations.AlterField(
            model_name='cameracapture',
            name='effect',
            field=models.CharField(choices=[('none', 'Normal'), ('grayscale', 'Gri Tonlama'), ('edges', 'Kenar Algılama'), ('invert', 'Ters Çevir')], default='none', help_text='Uygulanan görüntü efekti', max_length=50, verbose_name='Efekt'),
        ),
        migrations.AlterField(
            model_name='cameracapture',
            name='pan_angle',
            field=models.FloatField(default=0.0, help_text='Yatay motor açısı (derece)', verbose_name='Pan Açısı (Yatay)'),
        ),
        migrations.AlterField(
            model_name='cameracapture',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Fotoğrafın çekildiği zaman', verbose_name='Zaman Damgası'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='h_scan_angle_setting',
            field=models.FloatField(default=360.0, verbose_name='Yatay Tarama Açısı (°)'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='h_step_angle_setting',
            field=models.FloatField(default=10.0, verbose_name='Yatay Adım Açısı (°)'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='v_scan_angle_setting',
            field=models.FloatField(default=180.0, verbose_name='Dikey Tarama Açısı (°)'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='v_step_angle_setting',
            field=models.FloatField(default=10.0, verbose_name='Dikey Adım Açısı (°)'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='derece',
            field=models.FloatField(help_text='Pan açısı', verbose_name='Yatay Açı (°)'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='dikey_aci',
            field=models.FloatField(blank=True, help_text='Tilt açısı', null=True, verbose_name='Dikey Açı (°)'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='mesafe_cm',
            field=models.FloatField(help_text='Birincil sensör okuması', verbose_name='Ana Mesafe (cm)'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='scan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='scanner.scan', verbose_name='Tarama'),
        ),
        migrations.AlterField(
            model_name='scanpoint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Zaman'),
        ),
        migrations.AddIndex(
            model_name='cameracapture',
            index=models.Index(fields=['-timestamp'], name='scanner_cam_timesta_c0f927_idx'),
        ),
        migrations.AddIndex(
            model_name='cameracapture',
            index=models.Index(fields=['effect'], name='scanner_cam_effect_9f36b9_idx'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['-timestamp', 'level'], name='scanner_sys_timesta_dcc399_idx'),
        ),
    ]
